export const data = [
    {
      rank: 1,
      name: "Selling with re entr",
      calmar: 3.96,
      profit: 381845,
      avgProfit: 319.54,
      winPercentage: 0.65,
      price: 0,
      action: "View",
    },
    {
      rank: 2,
      name: "strategy_name",
      calmar: 3.62,
      profit: 268872.5,
      avgProfit: 216.31,
      winPercentage: 0.64,
      price: 500,
      action: "Buy",
    },
    {
      rank: 3,
      name: "Based on premium and",
      calmar: 3.42,
      profit: 255425,
      avgProfit: 208.51,
      winPercentage: 0.64,
      price: 0,
      action: "View",
    },
    {
        rank: 4,
        name: "strategy_name",
        calmar: 4.42,
        profit: 455425,
        avgProfit: 438.51,
        winPercentage: 0.34,
        price: 0,
        action: "View",
      },
      {
        rank: 5,
        name: "Based on premium and",
        calmar: 4.42,
        profit: 355425,
        avgProfit: 568.51,
        winPercentage: 0.64,
        price: 0,
        action: "View",
      },
      {
        rank: 6,
        name: "Based on premium and",
        calmar: 3.42,
        profit: 445425,
        avgProfit: 243.51,
        winPercentage: 0.34,
        price: 0,
        action: "View",
      },
    // Add more data as needed
  ];